- name: route53 configuration
  hosts: local
  connection: local
  vars:
    VPC_ID: subnet-04765d0a904a216d3
    type_of_instance: "t2.micro"
    security_group_id: "sg-0b8022285026f7d1e"
    images_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: AWS ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{VPC_ID}}"
      instance_type: "{{type_of_instance}}"
      security_group: "{{security_group_id}}"
      image_id: "{{images_id}}"
    loop: "{{instances}}"
    register: ec2_instances
    ansible.bulitin.debug:
      msg: "{{ec2_instances}}"