- name: install of multiple Packages
  hosts: local
  connection: local
  tasks:
  - name: Packages install
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - postgresql16-server
    - nginx
    - mysql
    - http
    - java