- name: installation of MYSQL DB
  hosts: web
  become: yes
  tasks:
  - name: installation of Mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: present
  - name: enable the services & start the service
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started
  - name: installation of nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: absent
    ansible.builtin.dnf:
      name: nodejs:20
      state: present