- name: nginx install and run
  hosts: web
  become: yes # sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
  - name: start the nginx service
    ansible.builtin.service:
      name: nginx
      state: started