- name: variables from inventory
  hosts: web
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "Hi This is {{Name}}. I'm learning {{Course}}"


      # ansible-playbook -i inventory.ini command.yml