- name: variables to print
  hosts: web
  vars:
    Name: "HemanthKumar"
    course: "DevOps" 
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi this is Hemanth_kumar. I'm learning the Devops"
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi this is {{Name}}. I'm learning the {{course}}"
  - name: print the information
    vars: 
      course: "Ansible" #Task level variable
    ansible.builtin.debug:
      msg: "Hi this is {{Name}}. I'm learning the {{course}}"

#1. command linie/arguments
#2. task level
#3. files
#4. prompt
#5. play level
#6. inventory
#7. role based